# Generated by Django 4.1.2 on 2022-11-07 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CellRangeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Define when a sheet has created.",
                        verbose_name="セル範囲作成日時",
                    ),
                ),
                (
                    "sheet_update_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Define when a sheet has updated.",
                        verbose_name="セル範囲作成日時",
                    ),
                ),
                (
                    "cell_range_id",
                    models.UUIDField(
                        default=uuid.UUID("12764861-f3e2-45ee-983f-f531d975d097"),
                        help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                        verbose_name="セル範囲ID",
                    ),
                ),
                (
                    "cell_range_id_by_order",
                    models.IntegerField(
                        default=None,
                        help_text="An ID based on merged order is assigned by cell range.",
                        verbose_name="順序付きセル範囲ID",
                    ),
                ),
            ],
            options={"db_table": "cell_range",},
        ),
        migrations.CreateModel(
            name="ESTemplateNamesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="profile", max_length=20, verbose_name="シートタイプ"
                    ),
                ),
            ],
            options={"db_table": "template_names",},
        ),
        migrations.CreateModel(
            name="RowModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_start",
                    models.CharField(
                        default="A1", max_length=10, verbose_name="セルのロー初期位置"
                    ),
                ),
                (
                    "cell_end",
                    models.CharField(
                        default="A1", max_length=10, verbose_name="セルのロー終端位置"
                    ),
                ),
                (
                    "cell_range_id_by_order",
                    models.IntegerField(
                        default=None,
                        help_text="An ID based on merged order is assigned by cell range.",
                        verbose_name="順序付きセル範囲ID",
                    ),
                ),
                (
                    "cell_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="upload_excel.cellrangemodel",
                    ),
                ),
            ],
            options={"db_table": "row",},
        ),
        migrations.CreateModel(
            name="ExcelSheetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Define when a sheet has created.",
                        verbose_name="シート作成日時",
                    ),
                ),
                (
                    "sheet_update_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Define when a sheet has updated.",
                        verbose_name="シート作成日時",
                    ),
                ),
                (
                    "sheet_id",
                    models.UUIDField(
                        default=uuid.UUID("312b9497-1b17-4253-a3a8-ab8e07d1be39"),
                        help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                        verbose_name="シートID",
                    ),
                ),
                (
                    "sheet_type",
                    models.CharField(
                        choices=[(1, "profile"), (2, "project")],
                        default="profile",
                        help_text="Set a name of template sheet.'profile' that is default sheet type is a template we designed as typical profile in our officeEven before you don't generate your custom template, you can use two template types of 'profile' and 'project'",
                        max_length=10,
                        verbose_name="シートタイプ",
                    ),
                ),
                (
                    "excel_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_sheet",
                        to="upload_excel.estemplatenamesmodel",
                    ),
                ),
            ],
            options={"db_table": "excel_sheet",},
        ),
        migrations.CreateModel(
            name="ContentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_content", models.TextField(default="", verbose_name="セルの内容")),
                (
                    "cell_range_id_by_order",
                    models.IntegerField(
                        default=None,
                        help_text="An ID based on merged order is assigned by cell range.",
                        verbose_name="順序付きセル範囲ID",
                    ),
                ),
                (
                    "cell_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="upload_excel.cellrangemodel",
                    ),
                ),
            ],
            options={"db_table": "content",},
        ),
        migrations.CreateModel(
            name="ColumnModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_start",
                    models.CharField(
                        default="A1", max_length=10, verbose_name="セルのカラム初期位置"
                    ),
                ),
                (
                    "cell_end",
                    models.CharField(
                        default="A1", max_length=10, verbose_name="セルのカラム終端位置"
                    ),
                ),
                (
                    "cell_range_id_by_order",
                    models.IntegerField(
                        default=None,
                        help_text="An ID based on merged order is assigned by cell range.",
                        verbose_name="順序付きセル範囲ID",
                    ),
                ),
                (
                    "cell_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="upload_excel.cellrangemodel",
                    ),
                ),
            ],
            options={"db_table": "column",},
        ),
        migrations.AddField(
            model_name="cellrangemodel",
            name="excel_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cell_ranges",
                to="upload_excel.excelsheetmodel",
            ),
        ),
    ]
