# Generated by Django 4.1.2 on 2022-11-10 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload_excel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellrangemodel",
            name="is_dev_exp_id",
            field=models.BooleanField(default=False, verbose_name="開発経験IDかどうか"),
        ),
        migrations.AlterField(
            model_name="cellrangemodel",
            name="cell_range_id",
            field=models.UUIDField(
                default=uuid.UUID("8076733f-f5df-4484-8783-924031cdffc5"),
                help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                verbose_name="セル範囲ID",
            ),
        ),
        migrations.AlterField(
            model_name="excelsheetmodel",
            name="sheet_id",
            field=models.UUIDField(
                default=uuid.UUID("71be056c-bcf0-432f-ade2-99661ad7f9aa"),
                help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                primary_key=True,
                serialize=False,
                verbose_name="シートID",
            ),
        ),
    ]
