# Generated by Django 4.1.2 on 2022-11-08 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload_excel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnmodel",
            name="cell_size",
            field=models.PositiveIntegerField(default=1, verbose_name="セルの列方向サイズ"),
        ),
        migrations.AddField(
            model_name="rowmodel",
            name="cell_size",
            field=models.PositiveIntegerField(default=1, verbose_name="セルの行方向サイズ"),
        ),
        migrations.AlterField(
            model_name="cellrangemodel",
            name="cell_range_id",
            field=models.UUIDField(
                default=uuid.UUID("fd9bc026-b99e-4706-933b-9e660121835f"),
                help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                verbose_name="セル範囲ID",
            ),
        ),
        migrations.AlterField(
            model_name="excelsheetmodel",
            name="sheet_id",
            field=models.UUIDField(
                default=uuid.UUID("2f178238-cae5-4274-b07c-e2a86d44fe16"),
                help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                primary_key=True,
                serialize=False,
                verbose_name="シートID",
            ),
        ),
    ]
