# Generated by Django 4.1.2 on 2022-11-07 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload_excel", "0002_alter_cellrangemodel_cell_range_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="excelsheetmodel", name="excel_template",),
        migrations.AlterField(
            model_name="cellrangemodel",
            name="cell_range_id",
            field=models.UUIDField(
                default=uuid.UUID("17dae61e-5b1e-4dde-a7f5-0ef0eddf4f0d"),
                help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                verbose_name="セル範囲ID",
            ),
        ),
        migrations.AlterField(
            model_name="excelsheetmodel",
            name="sheet_id",
            field=models.UUIDField(
                default=uuid.UUID("62d1da89-7f7e-4146-9d28-fe2981695ddf"),
                help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                verbose_name="シートID",
            ),
        ),
    ]
