# Generated by Django 4.1.2 on 2022-11-11 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload_excel", "0003_cellrangemodel_include_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellrangemodel",
            name="is_end_of_sheet",
            field=models.BooleanField(default=False, verbose_name="シートの最後かどうか"),
        ),
        migrations.AlterField(
            model_name="cellrangemodel",
            name="cell_range_id",
            field=models.UUIDField(
                default=uuid.UUID("a1e01a87-e267-47e2-89d5-32b896808a7c"),
                help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                verbose_name="セル範囲ID",
            ),
        ),
        migrations.AlterField(
            model_name="excelsheetmodel",
            name="sheet_id",
            field=models.UUIDField(
                default=uuid.UUID("508594b2-51b6-40af-9322-78fd94329317"),
                help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                primary_key=True,
                serialize=False,
                verbose_name="シートID",
            ),
        ),
    ]
