# Generated by Django 4.1.2 on 2022-11-11 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload_excel", "0004_cellrangemodel_is_end_of_sheet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellrangemodel",
            name="is_space",
            field=models.BooleanField(default=False, verbose_name="マージンかどうか"),
        ),
        migrations.AlterField(
            model_name="cellrangemodel",
            name="cell_range_id",
            field=models.UUIDField(
                default=uuid.UUID("dddeed83-db3f-483e-b8c6-11b8c55b1ebf"),
                help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                verbose_name="セル範囲ID",
            ),
        ),
        migrations.AlterField(
            model_name="excelsheetmodel",
            name="sheet_id",
            field=models.UUIDField(
                default=uuid.UUID("6378f13d-b133-47c0-be00-19a10cd394bc"),
                help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                primary_key=True,
                serialize=False,
                verbose_name="シートID",
            ),
        ),
    ]
