# Generated by Django 4.1.2 on 2022-11-11 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("upload_excel", "0005_cellrangemodel_is_space_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cellrangemodel",
            name="cell_range_id",
            field=models.UUIDField(
                default=uuid.UUID("5b0e8da0-fa02-4c5c-8384-a281e2ad05b4"),
                help_text="An ID based on uuid4 is assigned by cell range randomly and automatically.",
                verbose_name="セル範囲ID",
            ),
        ),
        migrations.AlterField(
            model_name="excelsheetmodel",
            name="sheet_id",
            field=models.UUIDField(
                default=uuid.UUID("fe7c34b7-93ed-45d5-8b22-a0673c601bd5"),
                help_text="An ID based on uuid4 is assigned by sheet randomly and automatically.",
                primary_key=True,
                serialize=False,
                verbose_name="シートID",
            ),
        ),
    ]
