# Generated by Django 4.1.2 on 2022-11-11 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadedExcelSheetModel",
            fields=[
                (
                    "downloaded_key",
                    models.UUIDField(
                        default=uuid.UUID("0f9e59c5-86c4-4bc1-9f39-611ca48e4e6c"),
                        primary_key=True,
                        serialize=False,
                        verbose_name="ダウンロードされたエクセルシートID",
                    ),
                ),
            ],
            options={"db_table": "downloaded_excel_sheet",},
        ),
    ]
